Update patch set 1
Patch Set 1:

BUILD FAILURE POSTMORTEM (from earlier build):

[2020-11-11T01:02:59.319Z] scons: building `build/debug/zookeeper/zookeeper_client.o' because it doesn't exist
[2020-11-11T01:02:59.319Z] C++ build/debug/zookeeper/zookeeper_client.o
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooCreate(zhandle_t*, const char*, const char*, int, const ACL_vector*, int, char*, int)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:56:28: error: â€˜zoo_createâ€™ was not declared in this scope
[2020-11-11T01:03:00.692Z]              path_buffer_len);
[2020-11-11T01:03:00.692Z]                             ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooDelete(zhandle_t*, const char*, int)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:59:44: error: â€˜zoo_deleteâ€™ was not declared in this scope
[2020-11-11T01:03:00.692Z]          return zoo_delete(zh, path, version);
[2020-11-11T01:03:00.692Z]                                             ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooGet(zhandle_t*, const char*, int, char*, int*, Stat*)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:63:65: error: â€˜zoo_getâ€™ was not declared in this scope
[2020-11-11T01:03:00.692Z]          return zoo_get(zh, path, watch, buffer, buffer_len, stat);
[2020-11-11T01:03:00.692Z]                                                                  ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooExists(zhandle_t*, const char*, int, Stat*)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:67:48: error: â€˜zoo_existsâ€™ was not declared in this scope
[2020-11-11T01:03:00.692Z]          return zoo_exists(zh, path, watch, stat);
[2020-11-11T01:03:00.692Z]                                                 ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:68:5: error: control reaches end of non-void function [-Werror=return-type]
[2020-11-11T01:03:00.692Z]      }
[2020-11-11T01:03:00.692Z]      ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooGet(zhandle_t*, const char*, int, char*, int*, Stat*)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:64:5: error: control reaches end of non-void function [-Werror=return-type]
[2020-11-11T01:03:00.692Z]      }
[2020-11-11T01:03:00.692Z]      ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooDelete(zhandle_t*, const char*, int)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:60:5: error: control reaches end of non-void function [-Werror=return-type]
[2020-11-11T01:03:00.692Z]      }
[2020-11-11T01:03:00.692Z]      ^
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc: In member function â€˜virtual int zookeeper::interface::ZookeeperCBindings::ZooCreate(zhandle_t*, const char*, const char*, int, const ACL_vector*, int, char*, int)â€™:
[2020-11-11T01:03:00.692Z] src/contrail-common/zookeeper/zookeeper_client.cc:57:5: error: control reaches end of non-void function [-Werror=return-type]
[2020-11-11T01:03:00.692Z]      }
[2020-11-11T01:03:00.692Z]      ^
[2020-11-11T01:03:00.692Z] cc1plus: all warnings being treated as errors
[2020-11-11T01:03:00.692Z] scons: *** [build/debug/zookeeper/zookeeper_client.o] Error 1

Patch-set: 1
Reviewer: Gerrit User 923 <923@c72cd27d-1743-4a55-84a4-cd13b8400c52>