Fixing bitarray library issue
Recent version of bitarray do not support length function
NotImplementedError: self.length() has been deprecated since 1.5.1, and was removed in 2.0.0.
Use len(self) instead.

Closes-Jira-Bug: CEM-21811

Change-Id: I9fc156f227e168b0f7e5938c0d25622411f1a859
Signed-off-by: Sayali Mane <smane@juniper.net>