Issue : CEM-26801 Fabric snat feature does not push __contrail_overlay_fip_snat__ group
Rootcause : In contrail-device-manager.log there is failure with below error :
File "/usr/lib/python2.7/site-packages/device_manager/dc_gateway_feature.py", line 638, in construct_cgnat_config
self.add_routing_instance(ri_conf)
AttributeError: 'DcGatewayFeature' object has no attribute 'add_routing_instance'

Here the  incorrect api “add_routing_instance”  being called .
The correct api is  “_add_routing_instance”.

Fix :  Is to call correct api  “_add_routing_instance”  from api “construct_cgnat_config”

Signed-off-by: Haritha Reddy <harithar@juniper.net>
Change-Id: If9eb1fbcc65930ff70b11ab11259d8ba7e7e4326